import { RESEARCH_CATEGORIES, ResearchDefinitionSeed } from '../game/research/research.schema';

export const researchSeedData: ResearchDefinitionSeed[] = [
  // === DEFENSE TECHNOLOGIES ===
  {
    code: 'defense1',
    name: 'Basic Armor',
    tier: 1,
    category: RESEARCH_CATEGORIES.DEFENSE,
    primaryEffect: '+25% defense HP for all defensive structures and ships',
    description: 'Improved armor plating technology increases the durability of defensive systems',
    unlocks: ['Defense Platform', 'Armored variants of basic ships'],
  },
  {
    code: 'defense2',
    name: 'Shield Technology',
    tier: 1,
    category: RESEARCH_CATEGORIES.DEFENSE,
    primaryEffect: '+20% shield capacity for all structures and ships with shields',
    description: 'Basic energy shield generators provide additional protection',
    unlocks: ['Shield Generator', 'Shielded variants of structures'],
  },
  {
    code: 'defense3',
    name: 'Advanced Armor',
    tier: 2,
    category: RESEARCH_CATEGORIES.DEFENSE,
    primaryEffect: '+50% defense HP for all defensive structures and ships',
    description: 'Composite armor materials provide superior protection',
    unlocks: ['Heavy Defense Platform', 'Heavily armored ship variants'],
  },
  {
    code: 'defense4',
    name: 'Advanced Shields',
    tier: 2,
    category: RESEARCH_CATEGORIES.DEFENSE,
    primaryEffect: '+40% shield capacity and +25% shield regeneration',
    description: 'Enhanced shield technology with improved power efficiency',
    unlocks: ['Advanced Shield Generator', 'Capital ship shield systems'],
  },

  // === WEAPONS TECHNOLOGIES ===
  {
    code: 'weapons1',
    name: 'Kinetic Weapons',
    tier: 1,
    category: RESEARCH_CATEGORIES.WEAPONS,
    primaryEffect: '+25% damage for all kinetic weapons',
    description: 'Improved projectile weapons with enhanced velocity and impact',
    unlocks: ['Kinetic Defense Battery', 'Ranger Scout', 'Dart Fighter'],
  },
  {
    code: 'weapons2',
    name: 'Energy Weapons',
    tier: 1,
    category: RESEARCH_CATEGORIES.WEAPONS,
    primaryEffect: '+25% damage for all energy weapons',
    description: 'Basic laser and beam weapon technology',
    unlocks: ['Energy Defense Array', 'Beam-armed ships'],
  },
  {
    code: 'weapons3',
    name: 'Advanced Kinetics',
    tier: 2,
    category: RESEARCH_CATEGORIES.WEAPONS,
    primaryEffect: '+50% damage for all kinetic weapons',
    description: 'Railgun and mass driver technology for devastating kinetic strikes',
    unlocks: ['Heavy Kinetic Battery', 'Sentinel Frigate', 'Guardian Destroyer'],
  },
  {
    code: 'weapons4',
    name: 'Plasma Weapons',
    tier: 2,
    category: RESEARCH_CATEGORIES.WEAPONS,
    primaryEffect: '+50% damage for all energy weapons',
    description: 'Superheated plasma projection systems',
    unlocks: ['Plasma Defense Grid', 'Tempest Strike Ship', 'Energy-focused cruisers'],
  },
  {
    code: 'weapons5',
    name: 'Quantum Weapons',
    tier: 3,
    category: RESEARCH_CATEGORIES.WEAPONS,
    primaryEffect: '+100% damage for all weapons',
    description: 'Reality-altering quantum field manipulation weapons',
    unlocks: ['Quantum Defense Array', 'Nova Leviathan', 'Apocalypse Dreadnought'],
  },

  // === SHIPS TECHNOLOGIES ===
  {
    code: 'ships1',
    name: 'Chemical Propulsion',
    tier: 1,
    category: RESEARCH_CATEGORIES.SHIPS,
    primaryEffect: '+25% ship speed and maneuverability',
    description: 'Basic chemical rocket engines for space travel',
    unlocks: ['Genesis Colonizer', 'Basic civilian ships'],
  },
  {
    code: 'ships2',
    name: 'Small Ship Design',
    tier: 1,
    category: RESEARCH_CATEGORIES.SHIPS,
    primaryEffect: 'Enables construction of small military vessels',
    description: 'Fundamental spacecraft engineering for small combat vessels',
    unlocks: ['Requires weapon tech for specific ship variants'],
  },
  {
    code: 'ships3',
    name: 'Ion Propulsion',
    tier: 2,
    category: RESEARCH_CATEGORIES.SHIPS,
    primaryEffect: '+50% ship speed and maneuverability',
    description: 'Efficient ion drive technology for extended space operations',
    unlocks: ['Void Harvester', 'Long-range exploration ships'],
  },
  {
    code: 'ships4',
    name: 'Medium Ship Design',
    tier: 2,
    category: RESEARCH_CATEGORIES.SHIPS,
    primaryEffect: 'Enables construction of cruiser-class vessels',
    description: 'Advanced hull design and systems integration for larger warships',
    unlocks: ['Dauntless Cruiser', 'Intrepid Carrier Cruiser'],
  },
  {
    code: 'ships5',
    name: 'Quantum Drive',
    tier: 3,
    category: RESEARCH_CATEGORIES.SHIPS,
    primaryEffect: '+100% ship speed and enables faster-than-light travel',
    description: 'Quantum field manipulation for near-instantaneous travel',
    unlocks: ['Capital ship mobility', 'Strategic redeployment capabilities'],
  },
  {
    code: 'ships6',
    name: 'Capital Ship Design',
    tier: 3,
    category: RESEARCH_CATEGORIES.SHIPS,
    primaryEffect: 'Enables construction of battleship and dreadnought-class vessels',
    description: 'Massive warship architecture and life support systems',
    unlocks: ['Juggernaut Battleship', 'Sovereign Dreadnought', 'Colossus Carrier'],
  },

  // === STRUCTURES TECHNOLOGIES ===
  {
    code: 'structures1',
    name: 'Basic Infrastructure',
    tier: 1,
    category: RESEARCH_CATEGORIES.STRUCTURES,
    primaryEffect: 'Enables basic colony buildings',
    description: 'Fundamental construction and life support technologies',
    unlocks: ['Hab Dome', 'Power Plant', 'Construction Yard'],
  },
  {
    code: 'structures2',
    name: 'Scientific Method',
    tier: 1,
    category: RESEARCH_CATEGORIES.STRUCTURES,
    primaryEffect: 'Enables research facilities and +25% research speed',
    description: 'Systematic approach to knowledge acquisition and experimentation',
    unlocks: ['Research Lab', 'Observatory'],
  },
  {
    code: 'structures3',
    name: 'Industrial Engineering',
    tier: 2,
    category: RESEARCH_CATEGORIES.STRUCTURES,
    primaryEffect: 'Enables advanced production and +25% construction speed',
    description: 'Automated manufacturing and resource processing systems',
    unlocks: ['Automated Fabricator', 'Mineral Refinery', 'Energy Nexus'],
  },
  {
    code: 'structures4',
    name: 'Advanced Research',
    tier: 2,
    category: RESEARCH_CATEGORIES.STRUCTURES,
    primaryEffect: 'Enables advanced research facilities and +50% research speed',
    description: 'Cutting-edge laboratory equipment and research methodologies',
    unlocks: ['Advanced Laboratory', 'Scientific Complex'],
  },
  {
    code: 'structures5',
    name: 'Megaengineering',
    tier: 3,
    category: RESEARCH_CATEGORIES.STRUCTURES,
    primaryEffect: 'Enables planetary-scale construction projects',
    description: 'Massive construction capabilities for world-spanning projects',
    unlocks: ['Orbital Habitat', 'Planetary Shield', 'Megastructure Hub'],
  },
  {
    code: 'structures6',
    name: 'Quantum Computing',
    tier: 3,
    category: RESEARCH_CATEGORIES.STRUCTURES,
    primaryEffect: 'Enables ultimate research facilities and +100% research speed',
    description: 'Quantum-scale computation for breakthrough discoveries',
    unlocks: ['Quantum Research Center', 'Theoretical Physics Institute'],
  },
];
