import { StructureDefinitionSeed, STRUCTURE_CATEGORIES } from '../game/bases/bases.schema';

export const structuresSeedData: StructureDefinitionSeed[] = [
  // Habitat Structures
  {
    name: 'Hab Dome',
    category: STRUCTURE_CATEGORIES.HABITAT,
    description: 'Hab Dome',
    baseSpaceCost: 5,
    baseEnergyCost: 2,
    baseNovaCost: 300,
    effects: '=+10 Space',
    upgradeBenefits: '=+5 Space per level',
  },
  {
    name: 'Terraforming Station',
    category: STRUCTURE_CATEGORIES.HABITAT,
    description: 'Terraforming Station',
    baseSpaceCost: 8,
    baseEnergyCost: 3,
    baseNovaCost: 500,
    researchRequirementName: 'Planetary Adaptation',
    effects: '=+15 Space, -1 Volatiles',
    upgradeBenefits: '=+8 Space per level',
  },
  {
    name: 'Orbital Habitat',
    category: STRUCTURE_CATEGORIES.HABITAT,
    description: 'Orbital Habitat',
    baseSpaceCost: 12,
    baseEnergyCost: 4,
    baseNovaCost: 800,
    researchRequirementName: 'Zero-G Construction',
    effects: '=+20 Space, +1 Research',
    upgradeBenefits: '=+10 Space per level',
  },
  {
    name: 'Subterranean Complex',
    category: STRUCTURE_CATEGORIES.HABITAT,
    description: 'Subterranean Complex',
    baseSpaceCost: 15,
    baseEnergyCost: 5,
    baseNovaCost: 1200,
    researchRequirementName: 'Advanced Excavation',
    effects: '=+25 Space, +1 Minerals',
    upgradeBenefits: '=+12 Space per level, +0.5 Minerals per level',
  },
  {
    name: 'Megastructure Hub',
    category: STRUCTURE_CATEGORIES.HABITAT,
    description: 'Megastructure Hub',
    baseSpaceCost: 25,
    baseEnergyCost: 8,
    baseNovaCost: 2000,
    researchRequirementName: 'Megaengineering',
    effects: '=+40 Space, +2 Energy',
    upgradeBenefits: '=+20 Space per level, +1 Energy per level',
  },

  // Construction Structures
  {
    name: 'Construction Yard',
    category: STRUCTURE_CATEGORIES.CONSTRUCTION,
    description: 'Construction Yard',
    baseSpaceCost: 8,
    baseEnergyCost: 3,
    baseNovaCost: 400,
    effects: '-10% Build Time',
    upgradeBenefits: '-5% Build Time per level',
  },
  {
    name: 'Automated Fabricator',
    category: STRUCTURE_CATEGORIES.CONSTRUCTION,
    description: 'Automated Fabricator',
    baseSpaceCost: 12,
    baseEnergyCost: 5,
    baseNovaCost: 700,
    researchRequirementName: 'Automation',
    effects: '-15% Build Time, +1 Minerals',
    upgradeBenefits: '-8% Build Time per level',
  },
  {
    name: 'Nanite Assembly',
    category: STRUCTURE_CATEGORIES.CONSTRUCTION,
    description: 'Nanite Assembly',
    baseSpaceCost: 15,
    baseEnergyCost: 7,
    baseNovaCost: 1100,
    researchRequirementName: 'Nanotechnology',
    effects: '-20% Build Time, +2 Minerals',
    upgradeBenefits: '-10% Build Time per level',
  },
  {
    name: 'Matter Compiler',
    category: STRUCTURE_CATEGORIES.CONSTRUCTION,
    description: 'Matter Compiler',
    baseSpaceCost: 20,
    baseEnergyCost: 10,
    baseNovaCost: 1800,
    researchRequirementName: 'Matter Manipulation',
    effects: '-30% Build Time, +3 Minerals',
    upgradeBenefits: '-15% Build Time per level',
  },
  {
    name: 'Quantum Constructor',
    category: STRUCTURE_CATEGORIES.CONSTRUCTION,
    description: 'Quantum Constructor',
    baseSpaceCost: 30,
    baseEnergyCost: 15,
    baseNovaCost: 3000,
    researchRequirementName: 'Quantum Engineering',
    effects: '-50% Build Time, +5 Minerals',
    upgradeBenefits: '-20% Build Time per level',
  },

  // Production Structures
  {
    name: 'Shipyard',
    category: STRUCTURE_CATEGORIES.PRODUCTION,
    description: 'Shipyard',
    baseSpaceCost: 10,
    baseEnergyCost: 5,
    baseNovaCost: 500,
    effects: 'Unlocks Basic Ships',
    upgradeBenefits: '=+10% Ship Production Speed per level',
  },
  {
    name: 'Advanced Shipyard',
    category: STRUCTURE_CATEGORIES.PRODUCTION,
    description: 'Advanced Shipyard',
    baseSpaceCost: 15,
    baseEnergyCost: 8,
    baseNovaCost: 900,
    researchRequirementName: 'Advanced Propulsion',
    effects: 'Unlocks Medium Ships',
    upgradeBenefits: '=+15% Ship Production Speed per level',
  },
  {
    name: 'Capital Shipyard',
    category: STRUCTURE_CATEGORIES.PRODUCTION,
    description: 'Capital Shipyard',
    baseSpaceCost: 25,
    baseEnergyCost: 12,
    baseNovaCost: 1500,
    researchRequirementName: 'Capital Ships',
    effects: 'Unlocks Heavy Ships',
    upgradeBenefits: '=+20% Ship Production Speed per level',
  },
  {
    name: 'Dreadnought Facility',
    category: STRUCTURE_CATEGORIES.PRODUCTION,
    description: 'Dreadnought Facility',
    baseSpaceCost: 35,
    baseEnergyCost: 20,
    baseNovaCost: 2500,
    researchRequirementName: 'Dreadnought Engineering',
    effects: 'Unlocks Dreadnoughts',
    upgradeBenefits: '=+25% Ship Production Speed per level',
  },
  {
    name: 'Star Forge',
    category: STRUCTURE_CATEGORIES.PRODUCTION,
    description: 'Star Forge',
    baseSpaceCost: 50,
    baseEnergyCost: 30,
    baseNovaCost: 4000,
    researchRequirementName: 'Stellar Engineering',
    effects: 'Unlocks Titan-class',
    upgradeBenefits: '=+30% Ship Production Speed per level',
  },

  // Research Structures
  {
    name: 'Research Lab',
    category: STRUCTURE_CATEGORIES.RESEARCH,
    description: 'Research Lab',
    baseSpaceCost: 8,
    baseEnergyCost: 4,
    baseNovaCost: 400,
    effects: '=+5 Research',
    upgradeBenefits: '=+3 Research per level',
  },
  {
    name: 'Advanced Laboratory',
    category: STRUCTURE_CATEGORIES.RESEARCH,
    description: 'Advanced Laboratory',
    baseSpaceCost: 12,
    baseEnergyCost: 6,
    baseNovaCost: 700,
    researchRequirementName: 'Advanced Analytics',
    effects: '=+8 Research',
    upgradeBenefits: '=+5 Research per level',
  },
  {
    name: 'Scientific Complex',
    category: STRUCTURE_CATEGORIES.RESEARCH,
    description: 'Scientific Complex',
    baseSpaceCost: 18,
    baseEnergyCost: 10,
    baseNovaCost: 1200,
    researchRequirementName: 'Complex Systems',
    effects: '=+12 Research',
    upgradeBenefits: '=+7 Research per level',
  },
  {
    name: 'Quantum Research Center',
    category: STRUCTURE_CATEGORIES.RESEARCH,
    description: 'Quantum Research Center',
    baseSpaceCost: 25,
    baseEnergyCost: 15,
    baseNovaCost: 2000,
    researchRequirementName: 'Quantum Computing',
    effects: '=+18 Research',
    upgradeBenefits: '=+10 Research per level',
  },
  {
    name: 'Theoretical Physics Institute',
    category: STRUCTURE_CATEGORIES.RESEARCH,
    description: 'Theoretical Physics Institute',
    baseSpaceCost: 35,
    baseEnergyCost: 20,
    baseNovaCost: 3000,
    researchRequirementName: 'Theoretical Physics',
    effects: '=+25 Research',
    upgradeBenefits: '=+15 Research per level',
  },

  // Economic Structures
  {
    name: 'Trading Post',
    category: STRUCTURE_CATEGORIES.ECONOMIC,
    description: 'Trading Post',
    baseSpaceCost: 6,
    baseEnergyCost: 2,
    baseNovaCost: 300,
    effects: '=+5 Nova/cycle',
    upgradeBenefits: '=+3 Nova/cycle per level',
  },
  {
    name: 'Mineral Refinery',
    category: STRUCTURE_CATEGORIES.ECONOMIC,
    description: 'Mineral Refinery',
    baseSpaceCost: 10,
    baseEnergyCost: 4,
    baseNovaCost: 600,
    researchRequirementName: 'Resource Refining',
    effects: '=+8 Nova/cycle',
    upgradeBenefits: '=+5 Nova/cycle per level',
  },
  {
    name: 'Volatile Processing',
    category: STRUCTURE_CATEGORIES.ECONOMIC,
    description: 'Volatile Processing',
    baseSpaceCost: 12,
    baseEnergyCost: 5,
    baseNovaCost: 800,
    researchRequirementName: 'Chemical Engineering',
    effects: '=+10 Nova/cycle',
    upgradeBenefits: '=+6 Nova/cycle per level',
  },
  {
    name: 'Galactic Market',
    category: STRUCTURE_CATEGORIES.ECONOMIC,
    description: 'Galactic Market',
    baseSpaceCost: 20,
    baseEnergyCost: 8,
    baseNovaCost: 1400,
    researchRequirementName: 'Galactic Economics',
    effects: '=+15 Nova/cycle',
    upgradeBenefits: '=+8 Nova/cycle per level',
  },
  {
    name: 'Stellar Exchange',
    category: STRUCTURE_CATEGORIES.ECONOMIC,
    description: 'Stellar Exchange',
    baseSpaceCost: 30,
    baseEnergyCost: 12,
    baseNovaCost: 2200,
    researchRequirementName: 'Financial Instruments',
    effects: '=+25 Nova/cycle',
    upgradeBenefits: '=+15 Nova/cycle per level',
  },

  // Utility Structures
  {
    name: 'Power Plant',
    category: STRUCTURE_CATEGORIES.UTILITY,
    description: 'Power Plant',
    baseSpaceCost: 10,
    baseEnergyCost: -5, // Note: Negative energy cost means it produces energy
    baseNovaCost: 400,
    effects: '=+10 Energy',
    upgradeBenefits: '=+5 Energy per level',
  },
  {
    name: 'Energy Nexus',
    category: STRUCTURE_CATEGORIES.UTILITY,
    description: 'Energy Nexus',
    baseSpaceCost: 15,
    baseEnergyCost: -10,
    baseNovaCost: 800,
    researchRequirementName: 'Advanced Energy',
    effects: '=+15 Energy',
    upgradeBenefits: '=+8 Energy per level',
  },
  {
    name: 'Mineral Extractor',
    category: STRUCTURE_CATEGORIES.UTILITY,
    description: 'Mineral Extractor',
    baseSpaceCost: 12,
    baseEnergyCost: 4,
    baseNovaCost: 600,
    researchRequirementName: 'Extraction Technology',
    effects: '=+5 Minerals',
    upgradeBenefits: '=+3 Minerals per level',
  },
  {
    name: 'Volatile Synthesizer',
    category: STRUCTURE_CATEGORIES.UTILITY,
    description: 'Volatile Synthesizer',
    baseSpaceCost: 12,
    baseEnergyCost: 5,
    baseNovaCost: 700,
    researchRequirementName: 'Molecular Synthesis',
    effects: '=+5 Volatiles',
    upgradeBenefits: '=+3 Volatiles per level',
  },
  {
    name: 'Planetary Shield',
    category: STRUCTURE_CATEGORIES.UTILITY,
    description: 'Planetary Shield',
    baseSpaceCost: 20,
    baseEnergyCost: 15,
    baseNovaCost: 1500,
    researchRequirementName: 'Shield Technology',
    effects: '=+20% Defense',
    upgradeBenefits: '=+10% Defense per level',
  },

  // Special Structures
  {
    name: 'Planetary Capital',
    category: STRUCTURE_CATEGORIES.SPECIAL,
    description: 'Planetary Capital',
    baseSpaceCost: 30,
    baseEnergyCost: 10,
    baseNovaCost: 2000,
    researchRequirementName: 'Planetary Governance',
    effects: '=+10% to all production',
    upgradeBenefits: '',
    maxLevel: 3,
  },
  {
    name: 'Stellar Observatory',
    category: STRUCTURE_CATEGORIES.SPECIAL,
    description: 'Stellar Observatory',
    baseSpaceCost: 15,
    baseEnergyCost: 8,
    baseNovaCost: 1200,
    researchRequirementName: 'Advanced Astronomy',
    effects: '=+15% Research Speed',
    upgradeBenefits: '',
    maxLevel: 3,
  },
  {
    name: 'Defense Matrix',
    category: STRUCTURE_CATEGORIES.SPECIAL,
    description: 'Defense Matrix',
    baseSpaceCost: 25,
    baseEnergyCost: 12,
    baseNovaCost: 1800,
    researchRequirementName: 'Defensive Systems',
    effects: '=+25% Base Defense',
    upgradeBenefits: '',
    maxLevel: 3,
  },
  {
    name: 'Interstellar Portal',
    category: STRUCTURE_CATEGORIES.SPECIAL,
    description: 'Interstellar Portal',
    baseSpaceCost: 40,
    baseEnergyCost: 25,
    baseNovaCost: 3500,
    researchRequirementName: 'Wormhole Technology',
    effects: 'Portal travel between bases',
    upgradeBenefits: '',
    maxLevel: 1,
  },
  {
    name: 'Cosmic Amplifier',
    category: STRUCTURE_CATEGORIES.SPECIAL,
    description: 'Cosmic Amplifier',
    baseSpaceCost: 35,
    baseEnergyCost: 20,
    baseNovaCost: 3000,
    researchRequirementName: 'Cosmic Energy',
    effects: '=+25% best resource',
    upgradeBenefits: '',
    maxLevel: 3,
  },
];
