export interface ShipBlueprint {
  id: string; // Unique identifier like "ranger_scout"
  name: string;
  category: string; // e.g., "Exploration Ships"
  novaCost: number;
  buildTimeCycles: number;
  requiredStructure: string;
  requiredTechnology: string;
  weaponType: string;
  damage: number;
  defense: number;
  shielding: number;
  movementSpeed?: number; // undefined for N/A (fighters)
  specialAbility: string;
  fleetCapacityCost: number;
  fighterCapacityProvided?: number;
}

export const shipBlueprintsData: ShipBlueprint[] = [
  // Exploration Ships
  {
    id: "ranger_scout",
    name: "Ranger Scout",
    category: "Exploration Ships",
    novaCost: 200,
    buildTimeCycles: 2,
    requiredStructure: "Shipyard",
    requiredTechnology: "Basic Propulsion",
    weaponType: "Kinetic",
    damage: 5,
    defense: 10,
    shielding: 0,
    movementSpeed: 5,
    specialAbility: "Enhanced Sensors",
    fleetCapacityCost: 0,
  },
  {
    id: "genesis_colonizer",
    name: "Genesis Colonizer",
    category: "Exploration Ships",
    novaCost: 1000,
    buildTimeCycles: 12,
    requiredStructure: "Advanced Shipyard",
    requiredTechnology: "Colonization",
    weaponType: "None",
    damage: 0,
    defense: 50,
    shielding: 20,
    movementSpeed: 2,
    specialAbility: "Planet Settlement",
    fleetCapacityCost: 0,
  },

  // Light Combat Ships
  {
    id: "dart_fighter",
    name: "Dart Fighter",
    category: "Light Combat Ships",
    novaCost: 150,
    buildTimeCycles: 2,
    requiredStructure: "Shipyard",
    requiredTechnology: "Fighter Technology",
    weaponType: "Kinetic",
    damage: 20,
    defense: 8,
    shielding: 0,
    // movementSpeed is undefined for fighters
    specialAbility: "Rapid Deployment",
    fleetCapacityCost: 0,
  },
  {
    id: "lance_interceptor",
    name: "Lance Interceptor",
    category: "Light Combat Ships",
    novaCost: 250,
    buildTimeCycles: 3,
    requiredStructure: "Shipyard",
    requiredTechnology: "Fighter Technology",
    weaponType: "Energy",
    damage: 25,
    defense: 10,
    shielding: 5,
    // movementSpeed is undefined for fighters
    specialAbility: "Anti-Fighter Specialization",
    fleetCapacityCost: 0,
  },
  {
    id: "havoc_bomber",
    name: "Havoc Bomber",
    category: "Light Combat Ships",
    novaCost: 400,
    buildTimeCycles: 5,
    requiredStructure: "Advanced Shipyard",
    requiredTechnology: "Advanced Ordinance",
    weaponType: "Explosive",
    damage: 40,
    defense: 15,
    shielding: 0,
    // movementSpeed is undefined for fighters
    specialAbility: "Capital Ship Damage Bonus",
    fleetCapacityCost: 0,
  },
  {
    id: "sentinel_frigate",
    name: "Sentinel Frigate",
    category: "Light Combat Ships",
    novaCost: 800,
    buildTimeCycles: 8,
    requiredStructure: "Shipyard",
    requiredTechnology: "Naval Architecture",
    weaponType: "Kinetic",
    damage: 40,
    defense: 50,
    shielding: 20,
    movementSpeed: 4,
    specialAbility: "Point Defense",
    fleetCapacityCost: 5,
  },
  {
    id: "horizon_escort",
    name: "Horizon Escort",
    category: "Light Combat Ships",
    novaCost: 1200,
    buildTimeCycles: 12,
    requiredStructure: "Advanced Shipyard",
    requiredTechnology: "Shield Technology",
    weaponType: "Energy",
    damage: 35,
    defense: 45,
    shielding: 50,
    movementSpeed: 4,
    specialAbility: "Enhanced Shielding",
    fleetCapacityCost: 8,
  },

  // Medium Combat Ships
  {
    id: "guardian_destroyer",
    name: "Guardian Destroyer",
    category: "Medium Combat Ships",
    novaCost: 1500,
    buildTimeCycles: 15,
    requiredStructure: "Advanced Shipyard",
    requiredTechnology: "Medium Ship Design",
    weaponType: "Missile",
    damage: 60,
    defense: 70,
    shielding: 40,
    movementSpeed: 3,
    specialAbility: "Anti-Ship Missiles",
    fleetCapacityCost: 10,
  },
  {
    id: "tempest_strike_ship",
    name: "Tempest Strike Ship",
    category: "Medium Combat Ships",
    novaCost: 1800,
    buildTimeCycles: 18,
    requiredStructure: "Advanced Shipyard",
    requiredTechnology: "Advanced Weaponry",
    weaponType: "Plasma",
    damage: 75,
    defense: 45,
    shielding: 30,
    movementSpeed: 4,
    specialAbility: "Rapid Strike Capability",
    fleetCapacityCost: 10,
  },
  {
    id: "dauntless_cruiser",
    name: "Dauntless Cruiser",
    category: "Medium Combat Ships",
    novaCost: 3000,
    buildTimeCycles: 25,
    requiredStructure: "Capital Shipyard",
    requiredTechnology: "Cruiser Design",
    weaponType: "Kinetic",
    damage: 90,
    defense: 80,
    shielding: 60,
    movementSpeed: 3,
    specialAbility: "Balanced Performance",
    fleetCapacityCost: 20,
  },
  {
    id: "harbinger_missile_cruiser",
    name: "Harbinger Missile Cruiser",
    category: "Medium Combat Ships",
    novaCost: 3500,
    buildTimeCycles: 28,
    requiredStructure: "Capital Shipyard",
    requiredTechnology: "Missile Systems",
    weaponType: "Missile",
    damage: 110,
    defense: 60,
    shielding: 50,
    movementSpeed: 3,
    specialAbility: "Long-Range Barrage",
    fleetCapacityCost: 18,
  },
  {
    id: "intrepid_carrier_cruiser",
    name: "Intrepid Carrier Cruiser",
    category: "Medium Combat Ships",
    novaCost: 4000,
    buildTimeCycles: 30,
    requiredStructure: "Capital Shipyard",
    requiredTechnology: "Carrier Operations",
    weaponType: "Energy",
    damage: 40,
    defense: 70,
    shielding: 50,
    movementSpeed: 3,
    specialAbility: "Fighter Support (carries 15 fighters)",
    fleetCapacityCost: 100,
    fighterCapacityProvided: 15,
  },

  // Heavy Combat Ships
  {
    id: "juggernaut_battleship",
    name: "Juggernaut Battleship",
    category: "Heavy Combat Ships",
    novaCost: 8000,
    buildTimeCycles: 50,
    requiredStructure: "Capital Shipyard",
    requiredTechnology: "Battleship Design",
    weaponType: "Kinetic",
    damage: 180,
    defense: 150,
    shielding: 100,
    movementSpeed: 2,
    specialAbility: "Heavy Bombardment",
    fleetCapacityCost: 50,
  },
  {
    id: "sovereign_dreadnought",
    name: "Sovereign Dreadnought",
    category: "Heavy Combat Ships",
    novaCost: 12000,
    buildTimeCycles: 65,
    requiredStructure: "Dreadnought Facility",
    requiredTechnology: "Dreadnought Architecture",
    weaponType: "Energy",
    damage: 220,
    defense: 180,
    shielding: 130,
    movementSpeed: 2,
    specialAbility: "Intimidation Aura (-15% enemy defense)",
    fleetCapacityCost: 65,
  },
  {
    id: "bastion_defense_battleship",
    name: "Bastion Defense Battleship",
    category: "Heavy Combat Ships",
    novaCost: 10000,
    buildTimeCycles: 60,
    requiredStructure: "Dreadnought Facility",
    requiredTechnology: "Advanced Defensive Systems",
    weaponType: "Energy",
    damage: 120,
    defense: 220,
    shielding: 160,
    movementSpeed: 2,
    specialAbility: "Shield Projection to nearby ships",
    fleetCapacityCost: 60,
  },
  {
    id: "colossus_carrier",
    name: "Colossus Carrier",
    category: "Heavy Combat Ships",
    novaCost: 15000,
    buildTimeCycles: 75,
    requiredStructure: "Dreadnought Facility",
    requiredTechnology: "Carrier Operations II",
    weaponType: "Missile",
    damage: 70,
    defense: 130,
    shielding: 100,
    movementSpeed: 2,
    specialAbility: "Massive Hangar (carries 40 fighters)",
    fleetCapacityCost: 500,
    fighterCapacityProvided: 40,
  },
  {
    id: "nova_leviathan",
    name: "Nova Leviathan",
    category: "Heavy Combat Ships",
    novaCost: 25000,
    buildTimeCycles: 100,
    requiredStructure: "Star Forge",
    requiredTechnology: "Advanced Capital Design",
    weaponType: "Plasma",
    damage: 300,
    defense: 250,
    shielding: 200,
    movementSpeed: 1,
    specialAbility: "Energy Surge Weapon",
    fleetCapacityCost: 120,
  },
  {
    id: "apocalypse_dreadnought",
    name: "Apocalypse Dreadnought",
    category: "Heavy Combat Ships",
    novaCost: 35000,
    buildTimeCycles: 150,
    requiredStructure: "Star Forge",
    requiredTechnology: "Apocalypse Weapons",
    weaponType: "Quantum",
    damage: 400,
    defense: 280,
    shielding: 220,
    movementSpeed: 1,
    specialAbility: "Nova Cannon (extreme damage)",
    fleetCapacityCost: 140,
  },

  // Specialized Ships
  {
    id: "void_harvester",
    name: "Void Harvester",
    category: "Specialized Ships",
    novaCost: 2000,
    buildTimeCycles: 20,
    requiredStructure: "Advanced Shipyard",
    requiredTechnology: "Resource Extraction",
    weaponType: "Energy",
    damage: 20,
    defense: 60,
    shielding: 30,
    movementSpeed: 3,
    specialAbility: "Asteroid Mining",
    fleetCapacityCost: 10,
  },
];
