import { internalMutation } from '@cvx/_generated/server';
import { StructureDefinitionSeed, STRUCTURE_CATEGORIES } from './bases.schema';

const defensiveStructuresSeedData: StructureDefinitionSeed[] = [
  // Basic Orbital Defenses
  {
    name: 'Orbital Platform',
    category: STRUCTURE_CATEGORIES.DEFENSE,
    description: 'Low orbit defense platform.',
    baseSpaceCost: 15,
    baseEnergyCost: 10,
    baseNovaCost: 1000,
    researchRequirementName: 'Orbital Defense',
    damage: 25,
    defense: 25,
    shielding: 5,
    effects: 'Low orbit defense',
    upgradeBenefits: '=+12 Damage, +12 Defense per level',
  },
  {
    name: 'Defense Satellite',
    category: STRUCTURE_CATEGORIES.DEFENSE,
    description: 'Satellite with an auto-targeting system.',
    baseSpaceCost: 12,
    baseEnergyCost: 12,
    baseNovaCost: 1200,
    researchRequirementName: 'Satellite Technology',
    damage: 35,
    defense: 15,
    shielding: 10,
    effects: 'Auto-targeting system',
    upgradeBenefits: '=+18 Damage, +5 Defense per level',
  },
  {
    name: 'Automated Minefield',
    category: STRUCTURE_CATEGORIES.DEFENSE,
    description: 'An area denial weapon system.',
    baseSpaceCost: 10,
    baseEnergyCost: 8,
    baseNovaCost: 900,
    researchRequirementName: 'Explosive Ordinance',
    damage: 30,
    defense: 20,
    shielding: 0,
    effects: 'Area denial weapon',
    upgradeBenefits: '=+15 Damage, +10 Defense per level',
  },
  {
    name: 'Early Warning System',
    category: STRUCTURE_CATEGORIES.DEFENSE,
    description: 'Provides increased reaction time against threats.',
    baseSpaceCost: 8,
    baseEnergyCost: 15,
    baseNovaCost: 800,
    researchRequirementName: 'Sensor Arrays',
    damage: 10,
    defense: 30,
    shielding: 15,
    effects: 'Increased reaction time',
    upgradeBenefits: '=+5 Damage, +15 Defense per level',
  },
  {
    name: 'Kinetic Defense Battery',
    category: STRUCTURE_CATEGORIES.DEFENSE,
    description: 'Utilizes mass accelerator weapons for defense.',
    baseSpaceCost: 18,
    baseEnergyCost: 12,
    baseNovaCost: 1500,
    researchRequirementName: 'Kinetic Weapons',
    damage: 40,
    defense: 20,
    shielding: 0,
    effects: 'Mass accelerator weapons',
    upgradeBenefits: '=+20 Damage, +10 Defense per level',
  },
  // Advanced Orbital Defenses
  {
    name: 'Ion Cannon',
    category: STRUCTURE_CATEGORIES.DEFENSE,
    description: 'A powerful focused beam weapon.',
    baseSpaceCost: 20,
    baseEnergyCost: 20,
    baseNovaCost: 1800,
    researchRequirementName: 'Beam Weapons',
    damage: 50,
    defense: 20,
    shielding: 15,
    effects: 'Powerful focused beam',
    upgradeBenefits: '=+25 Damage, +5 Shielding per level',
  },
  {
    name: 'Planetary Shield Generator',
    category: STRUCTURE_CATEGORIES.DEFENSE,
    description: 'Generates a full planetary shield.',
    baseSpaceCost: 25,
    baseEnergyCost: 30,
    baseNovaCost: 2500,
    researchRequirementName: 'Shield Technology',
    damage: 0,
    defense: 30,
    shielding: 50,
    effects: 'Full planetary shield',
    upgradeBenefits: '=+10 Defense, +25 Shielding per level',
  },
  {
    name: 'Orbital Defense Grid',
    category: STRUCTURE_CATEGORIES.DEFENSE,
    description: 'An integrated network of defensive platforms.',
    baseSpaceCost: 30,
    baseEnergyCost: 25,
    baseNovaCost: 2800,
    researchRequirementName: 'Defense Networks',
    damage: 45,
    defense: 40,
    shielding: 20,
    effects: 'Integrated defense network',
    upgradeBenefits: '=+20 Damage, +20 Defense per level',
  },
  {
    name: 'Stealth Field Generator',
    category: STRUCTURE_CATEGORIES.DEFENSE,
    description: 'Conceals the base from enemy sensors.',
    baseSpaceCost: 20,
    baseEnergyCost: 25,
    baseNovaCost: 2000,
    researchRequirementName: 'Stealth Systems',
    damage: 0,
    defense: 40,
    shielding: 30,
    effects: 'Conceals base from sensors',
    upgradeBenefits: '=+20 Defense, +15 Shielding per level',
  },
  {
    name: 'Electronic Warfare Array',
    category: STRUCTURE_CATEGORIES.DEFENSE,
    description: 'Disrupts enemy targeting systems.',
    baseSpaceCost: 15,
    baseEnergyCost: 20,
    baseNovaCost: 1800,
    researchRequirementName: 'Electronic Warfare',
    damage: 30,
    defense: 50,
    shielding: 10,
    effects: 'Disrupts enemy targeting',
    upgradeBenefits: '=+15 Damage, +25 Defense per level',
  },
  // Elite Defense Structures
  {
    name: 'Quantum Disruptor',
    category: STRUCTURE_CATEGORIES.DEFENSE,
    description: 'Employs phase-shifting attacks.',
    baseSpaceCost: 25,
    baseEnergyCost: 35,
    baseNovaCost: 3000,
    researchRequirementName: 'Quantum Technology',
    damage: 70,
    defense: 25,
    shielding: 20,
    effects: 'Phase-shifting attacks',
    upgradeBenefits: '=+35 Damage, +10 Defense per level',
  },
  {
    name: 'Graviton Projector',
    category: STRUCTURE_CATEGORIES.DEFENSE,
    description: 'A defense system based on gravitational manipulation.',
    baseSpaceCost: 30,
    baseEnergyCost: 40,
    baseNovaCost: 3500,
    researchRequirementName: 'Gravitational Physics',
    damage: 55,
    defense: 35,
    shielding: 30,
    effects: 'Gravity-based defense',
    upgradeBenefits: '=+25 Damage, +15 Defense, +10 Shielding per level',
  },
  {
    name: 'Plasma Defense Array',
    category: STRUCTURE_CATEGORIES.DEFENSE,
    description: 'An area denial system using plasma.',
    baseSpaceCost: 35,
    baseEnergyCost: 45,
    baseNovaCost: 4000,
    researchRequirementName: 'Plasma Systems',
    damage: 80,
    defense: 30,
    shielding: 25,
    effects: 'Area denial system',
    upgradeBenefits: '=+40 Damage, +10 Defense per level',
  },
  {
    name: 'Antimatter Mine Field',
    category: STRUCTURE_CATEGORIES.DEFENSE,
    description: 'A devastating area defense using antimatter mines.',
    baseSpaceCost: 30,
    baseEnergyCost: 35,
    baseNovaCost: 4000,
    researchRequirementName: 'Antimatter Technology',
    damage: 90,
    defense: 10,
    shielding: 0,
    effects: 'Devastating area defense',
    upgradeBenefits: '=+45 Damage per level',
  },
  {
    name: 'Nova Cannon',
    category: STRUCTURE_CATEGORIES.DEFENSE,
    description: 'A powerful planet-to-space weapon system.',
    baseSpaceCost: 50,
    baseEnergyCost: 60,
    baseNovaCost: 6000,
    researchRequirementName: 'Advanced Energy',
    damage: 100,
    defense: 25,
    shielding: 15,
    effects: 'Planet-to-space weapon',
    upgradeBenefits: '=+50 Damage, +10 Defense per level',
  },
];

export const seedDefensiveStructures = internalMutation(
  async (ctx) => {
    for (const structureData of defensiveStructuresSeedData) {
      // Check if researchRequirementName exists, if not, set to a default or handle as needed
      // For now, we assume it's always provided as per the seed data structure
      const dataToInsert: StructureDefinitionSeed = {
        ...structureData,
        // Ensure all required fields from StructureDefinitionSeed are present
        // Optional fields like maxLevel, imageUrl will be undefined if not in structureData
      };
      await ctx.db.insert('structureDefinitions', dataToInsert);
    }
    console.log(`Seeded ${defensiveStructuresSeedData.length} defensive structures.`);
    return `Seeded ${defensiveStructuresSeedData.length} defensive structures.`;
  }
);
