/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppAuthRouteImport } from './routes/_app/_auth'
import { Route as AppLoginLayoutRouteImport } from './routes/_app/login/_layout'
import { Route as AppLoginLayoutIndexRouteImport } from './routes/_app/login/_layout.index'
import { Route as AppAuthOnboardingLayoutRouteImport } from './routes/_app/_auth/onboarding/_layout'
import { Route as AppAuthDashboardLayoutRouteImport } from './routes/_app/_auth/dashboard/_layout'
import { Route as AppAuthGameLayoutRouteRouteImport } from './routes/_app/_auth/game/_layout/route'
import { Route as AppAuthGameLayoutIndexRouteImport } from './routes/_app/_auth/game/_layout/index'
import { Route as AppAuthDashboardLayoutIndexRouteImport } from './routes/_app/_auth/dashboard/_layout.index'
import { Route as AppAuthOnboardingLayoutUsernameRouteImport } from './routes/_app/_auth/onboarding/_layout.username'
import { Route as AppAuthGameLayoutOverviewRouteImport } from './routes/_app/_auth/game/_layout/overview'
import { Route as AppAuthGameLayoutFleetsRouteImport } from './routes/_app/_auth/game/_layout/fleets'
import { Route as AppAuthDashboardLayoutSettingsRouteImport } from './routes/_app/_auth/dashboard/_layout.settings'
import { Route as AppAuthDashboardLayoutCheckoutRouteImport } from './routes/_app/_auth/dashboard/_layout.checkout'
import { Route as AppAuthGameLayoutBasesIndexRouteImport } from './routes/_app/_auth/game/_layout/bases/index'
import { Route as AppAuthDashboardLayoutSettingsIndexRouteImport } from './routes/_app/_auth/dashboard/_layout.settings.index'
import { Route as AppAuthDashboardLayoutSettingsBillingRouteImport } from './routes/_app/_auth/dashboard/_layout.settings.billing'
import { Route as AppAuthGameLayoutBasesBaseIdIndexRouteImport } from './routes/_app/_auth/game/_layout/bases/$baseId/index'
import { Route as AppAuthGameLayoutmapMapIndexRouteImport } from './routes/_app/_auth/game/_layout/(map)/map.index'
import { Route as AppAuthGameLayoutmapMapGalaxyNumberRouteImport } from './routes/_app/_auth/game/_layout/(map)/map.$galaxyNumber'

const AppLoginRouteImport = createFileRoute('/_app/login')()
const AppAuthOnboardingRouteImport = createFileRoute('/_app/_auth/onboarding')()
const AppAuthDashboardRouteImport = createFileRoute('/_app/_auth/dashboard')()
const AppAuthGameRouteImport = createFileRoute('/_app/_auth/game')()

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLoginRoute = AppLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AppRoute,
} as any)
const AppAuthRoute = AppAuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => AppRoute,
} as any)
const AppAuthOnboardingRoute = AppAuthOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppAuthRoute,
} as any)
const AppAuthDashboardRoute = AppAuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppAuthRoute,
} as any)
const AppAuthGameRoute = AppAuthGameRouteImport.update({
  id: '/game',
  path: '/game',
  getParentRoute: () => AppAuthRoute,
} as any)
const AppLoginLayoutRoute = AppLoginLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => AppLoginRoute,
} as any)
const AppLoginLayoutIndexRoute = AppLoginLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppLoginLayoutRoute,
} as any)
const AppAuthOnboardingLayoutRoute = AppAuthOnboardingLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => AppAuthOnboardingRoute,
} as any)
const AppAuthDashboardLayoutRoute = AppAuthDashboardLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => AppAuthDashboardRoute,
} as any)
const AppAuthGameLayoutRouteRoute = AppAuthGameLayoutRouteRouteImport.update({
  id: '/_layout',
  getParentRoute: () => AppAuthGameRoute,
} as any)
const AppAuthGameLayoutIndexRoute = AppAuthGameLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAuthGameLayoutRouteRoute,
} as any)
const AppAuthDashboardLayoutIndexRoute =
  AppAuthDashboardLayoutIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppAuthDashboardLayoutRoute,
  } as any)
const AppAuthOnboardingLayoutUsernameRoute =
  AppAuthOnboardingLayoutUsernameRouteImport.update({
    id: '/username',
    path: '/username',
    getParentRoute: () => AppAuthOnboardingLayoutRoute,
  } as any)
const AppAuthGameLayoutOverviewRoute =
  AppAuthGameLayoutOverviewRouteImport.update({
    id: '/overview',
    path: '/overview',
    getParentRoute: () => AppAuthGameLayoutRouteRoute,
  } as any)
const AppAuthGameLayoutFleetsRoute = AppAuthGameLayoutFleetsRouteImport.update({
  id: '/fleets',
  path: '/fleets',
  getParentRoute: () => AppAuthGameLayoutRouteRoute,
} as any)
const AppAuthDashboardLayoutSettingsRoute =
  AppAuthDashboardLayoutSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AppAuthDashboardLayoutRoute,
  } as any)
const AppAuthDashboardLayoutCheckoutRoute =
  AppAuthDashboardLayoutCheckoutRouteImport.update({
    id: '/checkout',
    path: '/checkout',
    getParentRoute: () => AppAuthDashboardLayoutRoute,
  } as any)
const AppAuthGameLayoutBasesIndexRoute =
  AppAuthGameLayoutBasesIndexRouteImport.update({
    id: '/bases/',
    path: '/bases/',
    getParentRoute: () => AppAuthGameLayoutRouteRoute,
  } as any)
const AppAuthDashboardLayoutSettingsIndexRoute =
  AppAuthDashboardLayoutSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppAuthDashboardLayoutSettingsRoute,
  } as any)
const AppAuthDashboardLayoutSettingsBillingRoute =
  AppAuthDashboardLayoutSettingsBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => AppAuthDashboardLayoutSettingsRoute,
  } as any)
const AppAuthGameLayoutBasesBaseIdIndexRoute =
  AppAuthGameLayoutBasesBaseIdIndexRouteImport.update({
    id: '/bases/$baseId/',
    path: '/bases/$baseId/',
    getParentRoute: () => AppAuthGameLayoutRouteRoute,
  } as any)
const AppAuthGameLayoutmapMapIndexRoute =
  AppAuthGameLayoutmapMapIndexRouteImport.update({
    id: '/(map)/map/',
    path: '/map/',
    getParentRoute: () => AppAuthGameLayoutRouteRoute,
  } as any)
const AppAuthGameLayoutmapMapGalaxyNumberRoute =
  AppAuthGameLayoutmapMapGalaxyNumberRouteImport.update({
    id: '/(map)/map/$galaxyNumber',
    path: '/map/$galaxyNumber',
    getParentRoute: () => AppAuthGameLayoutRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof AppLoginLayoutRouteWithChildren
  '/game': typeof AppAuthGameLayoutRouteRouteWithChildren
  '/dashboard': typeof AppAuthDashboardLayoutRouteWithChildren
  '/onboarding': typeof AppAuthOnboardingLayoutRouteWithChildren
  '/login/': typeof AppLoginLayoutIndexRoute
  '/dashboard/checkout': typeof AppAuthDashboardLayoutCheckoutRoute
  '/dashboard/settings': typeof AppAuthDashboardLayoutSettingsRouteWithChildren
  '/game/fleets': typeof AppAuthGameLayoutFleetsRoute
  '/game/overview': typeof AppAuthGameLayoutOverviewRoute
  '/onboarding/username': typeof AppAuthOnboardingLayoutUsernameRoute
  '/dashboard/': typeof AppAuthDashboardLayoutIndexRoute
  '/game/': typeof AppAuthGameLayoutIndexRoute
  '/dashboard/settings/billing': typeof AppAuthDashboardLayoutSettingsBillingRoute
  '/dashboard/settings/': typeof AppAuthDashboardLayoutSettingsIndexRoute
  '/game/bases': typeof AppAuthGameLayoutBasesIndexRoute
  '/game/map/$galaxyNumber': typeof AppAuthGameLayoutmapMapGalaxyNumberRoute
  '/game/map': typeof AppAuthGameLayoutmapMapIndexRoute
  '/game/bases/$baseId': typeof AppAuthGameLayoutBasesBaseIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof AppLoginLayoutIndexRoute
  '/game': typeof AppAuthGameLayoutIndexRoute
  '/dashboard': typeof AppAuthDashboardLayoutIndexRoute
  '/onboarding': typeof AppAuthOnboardingLayoutRouteWithChildren
  '/dashboard/checkout': typeof AppAuthDashboardLayoutCheckoutRoute
  '/game/fleets': typeof AppAuthGameLayoutFleetsRoute
  '/game/overview': typeof AppAuthGameLayoutOverviewRoute
  '/onboarding/username': typeof AppAuthOnboardingLayoutUsernameRoute
  '/dashboard/settings/billing': typeof AppAuthDashboardLayoutSettingsBillingRoute
  '/dashboard/settings': typeof AppAuthDashboardLayoutSettingsIndexRoute
  '/game/bases': typeof AppAuthGameLayoutBasesIndexRoute
  '/game/map/$galaxyNumber': typeof AppAuthGameLayoutmapMapGalaxyNumberRoute
  '/game/map': typeof AppAuthGameLayoutmapMapIndexRoute
  '/game/bases/$baseId': typeof AppAuthGameLayoutBasesBaseIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/_auth': typeof AppAuthRouteWithChildren
  '/_app/login': typeof AppLoginRouteWithChildren
  '/_app/login/_layout': typeof AppLoginLayoutRouteWithChildren
  '/_app/_auth/game': typeof AppAuthGameRouteWithChildren
  '/_app/_auth/game/_layout': typeof AppAuthGameLayoutRouteRouteWithChildren
  '/_app/_auth/dashboard': typeof AppAuthDashboardRouteWithChildren
  '/_app/_auth/dashboard/_layout': typeof AppAuthDashboardLayoutRouteWithChildren
  '/_app/_auth/onboarding': typeof AppAuthOnboardingRouteWithChildren
  '/_app/_auth/onboarding/_layout': typeof AppAuthOnboardingLayoutRouteWithChildren
  '/_app/login/_layout/': typeof AppLoginLayoutIndexRoute
  '/_app/_auth/dashboard/_layout/checkout': typeof AppAuthDashboardLayoutCheckoutRoute
  '/_app/_auth/dashboard/_layout/settings': typeof AppAuthDashboardLayoutSettingsRouteWithChildren
  '/_app/_auth/game/_layout/fleets': typeof AppAuthGameLayoutFleetsRoute
  '/_app/_auth/game/_layout/overview': typeof AppAuthGameLayoutOverviewRoute
  '/_app/_auth/onboarding/_layout/username': typeof AppAuthOnboardingLayoutUsernameRoute
  '/_app/_auth/dashboard/_layout/': typeof AppAuthDashboardLayoutIndexRoute
  '/_app/_auth/game/_layout/': typeof AppAuthGameLayoutIndexRoute
  '/_app/_auth/dashboard/_layout/settings/billing': typeof AppAuthDashboardLayoutSettingsBillingRoute
  '/_app/_auth/dashboard/_layout/settings/': typeof AppAuthDashboardLayoutSettingsIndexRoute
  '/_app/_auth/game/_layout/bases/': typeof AppAuthGameLayoutBasesIndexRoute
  '/_app/_auth/game/_layout/(map)/map/$galaxyNumber': typeof AppAuthGameLayoutmapMapGalaxyNumberRoute
  '/_app/_auth/game/_layout/(map)/map/': typeof AppAuthGameLayoutmapMapIndexRoute
  '/_app/_auth/game/_layout/bases/$baseId/': typeof AppAuthGameLayoutBasesBaseIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/game'
    | '/dashboard'
    | '/onboarding'
    | '/login/'
    | '/dashboard/checkout'
    | '/dashboard/settings'
    | '/game/fleets'
    | '/game/overview'
    | '/onboarding/username'
    | '/dashboard/'
    | '/game/'
    | '/dashboard/settings/billing'
    | '/dashboard/settings/'
    | '/game/bases'
    | '/game/map/$galaxyNumber'
    | '/game/map'
    | '/game/bases/$baseId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/game'
    | '/dashboard'
    | '/onboarding'
    | '/dashboard/checkout'
    | '/game/fleets'
    | '/game/overview'
    | '/onboarding/username'
    | '/dashboard/settings/billing'
    | '/dashboard/settings'
    | '/game/bases'
    | '/game/map/$galaxyNumber'
    | '/game/map'
    | '/game/bases/$baseId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/_auth'
    | '/_app/login'
    | '/_app/login/_layout'
    | '/_app/_auth/game'
    | '/_app/_auth/game/_layout'
    | '/_app/_auth/dashboard'
    | '/_app/_auth/dashboard/_layout'
    | '/_app/_auth/onboarding'
    | '/_app/_auth/onboarding/_layout'
    | '/_app/login/_layout/'
    | '/_app/_auth/dashboard/_layout/checkout'
    | '/_app/_auth/dashboard/_layout/settings'
    | '/_app/_auth/game/_layout/fleets'
    | '/_app/_auth/game/_layout/overview'
    | '/_app/_auth/onboarding/_layout/username'
    | '/_app/_auth/dashboard/_layout/'
    | '/_app/_auth/game/_layout/'
    | '/_app/_auth/dashboard/_layout/settings/billing'
    | '/_app/_auth/dashboard/_layout/settings/'
    | '/_app/_auth/game/_layout/bases/'
    | '/_app/_auth/game/_layout/(map)/map/$galaxyNumber'
    | '/_app/_auth/game/_layout/(map)/map/'
    | '/_app/_auth/game/_layout/bases/$baseId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/login': {
      id: '/_app/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AppLoginRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/_auth': {
      id: '/_app/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppAuthRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/_auth/onboarding': {
      id: '/_app/_auth/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AppAuthOnboardingRouteImport
      parentRoute: typeof AppAuthRoute
    }
    '/_app/_auth/dashboard': {
      id: '/_app/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppAuthDashboardRouteImport
      parentRoute: typeof AppAuthRoute
    }
    '/_app/_auth/game': {
      id: '/_app/_auth/game'
      path: '/game'
      fullPath: '/game'
      preLoaderRoute: typeof AppAuthGameRouteImport
      parentRoute: typeof AppAuthRoute
    }
    '/_app/login/_layout': {
      id: '/_app/login/_layout'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AppLoginLayoutRouteImport
      parentRoute: typeof AppLoginRoute
    }
    '/_app/login/_layout/': {
      id: '/_app/login/_layout/'
      path: '/'
      fullPath: '/login/'
      preLoaderRoute: typeof AppLoginLayoutIndexRouteImport
      parentRoute: typeof AppLoginLayoutRoute
    }
    '/_app/_auth/onboarding/_layout': {
      id: '/_app/_auth/onboarding/_layout'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AppAuthOnboardingLayoutRouteImport
      parentRoute: typeof AppAuthOnboardingRoute
    }
    '/_app/_auth/dashboard/_layout': {
      id: '/_app/_auth/dashboard/_layout'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppAuthDashboardLayoutRouteImport
      parentRoute: typeof AppAuthDashboardRoute
    }
    '/_app/_auth/game/_layout': {
      id: '/_app/_auth/game/_layout'
      path: '/game'
      fullPath: '/game'
      preLoaderRoute: typeof AppAuthGameLayoutRouteRouteImport
      parentRoute: typeof AppAuthGameRoute
    }
    '/_app/_auth/game/_layout/': {
      id: '/_app/_auth/game/_layout/'
      path: '/'
      fullPath: '/game/'
      preLoaderRoute: typeof AppAuthGameLayoutIndexRouteImport
      parentRoute: typeof AppAuthGameLayoutRouteRoute
    }
    '/_app/_auth/dashboard/_layout/': {
      id: '/_app/_auth/dashboard/_layout/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AppAuthDashboardLayoutIndexRouteImport
      parentRoute: typeof AppAuthDashboardLayoutRoute
    }
    '/_app/_auth/onboarding/_layout/username': {
      id: '/_app/_auth/onboarding/_layout/username'
      path: '/username'
      fullPath: '/onboarding/username'
      preLoaderRoute: typeof AppAuthOnboardingLayoutUsernameRouteImport
      parentRoute: typeof AppAuthOnboardingLayoutRoute
    }
    '/_app/_auth/game/_layout/overview': {
      id: '/_app/_auth/game/_layout/overview'
      path: '/overview'
      fullPath: '/game/overview'
      preLoaderRoute: typeof AppAuthGameLayoutOverviewRouteImport
      parentRoute: typeof AppAuthGameLayoutRouteRoute
    }
    '/_app/_auth/game/_layout/fleets': {
      id: '/_app/_auth/game/_layout/fleets'
      path: '/fleets'
      fullPath: '/game/fleets'
      preLoaderRoute: typeof AppAuthGameLayoutFleetsRouteImport
      parentRoute: typeof AppAuthGameLayoutRouteRoute
    }
    '/_app/_auth/dashboard/_layout/settings': {
      id: '/_app/_auth/dashboard/_layout/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof AppAuthDashboardLayoutSettingsRouteImport
      parentRoute: typeof AppAuthDashboardLayoutRoute
    }
    '/_app/_auth/dashboard/_layout/checkout': {
      id: '/_app/_auth/dashboard/_layout/checkout'
      path: '/checkout'
      fullPath: '/dashboard/checkout'
      preLoaderRoute: typeof AppAuthDashboardLayoutCheckoutRouteImport
      parentRoute: typeof AppAuthDashboardLayoutRoute
    }
    '/_app/_auth/game/_layout/bases/': {
      id: '/_app/_auth/game/_layout/bases/'
      path: '/bases'
      fullPath: '/game/bases'
      preLoaderRoute: typeof AppAuthGameLayoutBasesIndexRouteImport
      parentRoute: typeof AppAuthGameLayoutRouteRoute
    }
    '/_app/_auth/dashboard/_layout/settings/': {
      id: '/_app/_auth/dashboard/_layout/settings/'
      path: '/'
      fullPath: '/dashboard/settings/'
      preLoaderRoute: typeof AppAuthDashboardLayoutSettingsIndexRouteImport
      parentRoute: typeof AppAuthDashboardLayoutSettingsRoute
    }
    '/_app/_auth/dashboard/_layout/settings/billing': {
      id: '/_app/_auth/dashboard/_layout/settings/billing'
      path: '/billing'
      fullPath: '/dashboard/settings/billing'
      preLoaderRoute: typeof AppAuthDashboardLayoutSettingsBillingRouteImport
      parentRoute: typeof AppAuthDashboardLayoutSettingsRoute
    }
    '/_app/_auth/game/_layout/bases/$baseId/': {
      id: '/_app/_auth/game/_layout/bases/$baseId/'
      path: '/bases/$baseId'
      fullPath: '/game/bases/$baseId'
      preLoaderRoute: typeof AppAuthGameLayoutBasesBaseIdIndexRouteImport
      parentRoute: typeof AppAuthGameLayoutRouteRoute
    }
    '/_app/_auth/game/_layout/(map)/map/': {
      id: '/_app/_auth/game/_layout/(map)/map/'
      path: '/map'
      fullPath: '/game/map'
      preLoaderRoute: typeof AppAuthGameLayoutmapMapIndexRouteImport
      parentRoute: typeof AppAuthGameLayoutRouteRoute
    }
    '/_app/_auth/game/_layout/(map)/map/$galaxyNumber': {
      id: '/_app/_auth/game/_layout/(map)/map/$galaxyNumber'
      path: '/map/$galaxyNumber'
      fullPath: '/game/map/$galaxyNumber'
      preLoaderRoute: typeof AppAuthGameLayoutmapMapGalaxyNumberRouteImport
      parentRoute: typeof AppAuthGameLayoutRouteRoute
    }
  }
}

interface AppAuthGameLayoutRouteRouteChildren {
  AppAuthGameLayoutFleetsRoute: typeof AppAuthGameLayoutFleetsRoute
  AppAuthGameLayoutOverviewRoute: typeof AppAuthGameLayoutOverviewRoute
  AppAuthGameLayoutIndexRoute: typeof AppAuthGameLayoutIndexRoute
  AppAuthGameLayoutBasesIndexRoute: typeof AppAuthGameLayoutBasesIndexRoute
  AppAuthGameLayoutmapMapGalaxyNumberRoute: typeof AppAuthGameLayoutmapMapGalaxyNumberRoute
  AppAuthGameLayoutmapMapIndexRoute: typeof AppAuthGameLayoutmapMapIndexRoute
  AppAuthGameLayoutBasesBaseIdIndexRoute: typeof AppAuthGameLayoutBasesBaseIdIndexRoute
}

const AppAuthGameLayoutRouteRouteChildren: AppAuthGameLayoutRouteRouteChildren =
  {
    AppAuthGameLayoutFleetsRoute: AppAuthGameLayoutFleetsRoute,
    AppAuthGameLayoutOverviewRoute: AppAuthGameLayoutOverviewRoute,
    AppAuthGameLayoutIndexRoute: AppAuthGameLayoutIndexRoute,
    AppAuthGameLayoutBasesIndexRoute: AppAuthGameLayoutBasesIndexRoute,
    AppAuthGameLayoutmapMapGalaxyNumberRoute:
      AppAuthGameLayoutmapMapGalaxyNumberRoute,
    AppAuthGameLayoutmapMapIndexRoute: AppAuthGameLayoutmapMapIndexRoute,
    AppAuthGameLayoutBasesBaseIdIndexRoute:
      AppAuthGameLayoutBasesBaseIdIndexRoute,
  }

const AppAuthGameLayoutRouteRouteWithChildren =
  AppAuthGameLayoutRouteRoute._addFileChildren(
    AppAuthGameLayoutRouteRouteChildren,
  )

interface AppAuthGameRouteChildren {
  AppAuthGameLayoutRouteRoute: typeof AppAuthGameLayoutRouteRouteWithChildren
}

const AppAuthGameRouteChildren: AppAuthGameRouteChildren = {
  AppAuthGameLayoutRouteRoute: AppAuthGameLayoutRouteRouteWithChildren,
}

const AppAuthGameRouteWithChildren = AppAuthGameRoute._addFileChildren(
  AppAuthGameRouteChildren,
)

interface AppAuthDashboardLayoutSettingsRouteChildren {
  AppAuthDashboardLayoutSettingsBillingRoute: typeof AppAuthDashboardLayoutSettingsBillingRoute
  AppAuthDashboardLayoutSettingsIndexRoute: typeof AppAuthDashboardLayoutSettingsIndexRoute
}

const AppAuthDashboardLayoutSettingsRouteChildren: AppAuthDashboardLayoutSettingsRouteChildren =
  {
    AppAuthDashboardLayoutSettingsBillingRoute:
      AppAuthDashboardLayoutSettingsBillingRoute,
    AppAuthDashboardLayoutSettingsIndexRoute:
      AppAuthDashboardLayoutSettingsIndexRoute,
  }

const AppAuthDashboardLayoutSettingsRouteWithChildren =
  AppAuthDashboardLayoutSettingsRoute._addFileChildren(
    AppAuthDashboardLayoutSettingsRouteChildren,
  )

interface AppAuthDashboardLayoutRouteChildren {
  AppAuthDashboardLayoutCheckoutRoute: typeof AppAuthDashboardLayoutCheckoutRoute
  AppAuthDashboardLayoutSettingsRoute: typeof AppAuthDashboardLayoutSettingsRouteWithChildren
  AppAuthDashboardLayoutIndexRoute: typeof AppAuthDashboardLayoutIndexRoute
}

const AppAuthDashboardLayoutRouteChildren: AppAuthDashboardLayoutRouteChildren =
  {
    AppAuthDashboardLayoutCheckoutRoute: AppAuthDashboardLayoutCheckoutRoute,
    AppAuthDashboardLayoutSettingsRoute:
      AppAuthDashboardLayoutSettingsRouteWithChildren,
    AppAuthDashboardLayoutIndexRoute: AppAuthDashboardLayoutIndexRoute,
  }

const AppAuthDashboardLayoutRouteWithChildren =
  AppAuthDashboardLayoutRoute._addFileChildren(
    AppAuthDashboardLayoutRouteChildren,
  )

interface AppAuthDashboardRouteChildren {
  AppAuthDashboardLayoutRoute: typeof AppAuthDashboardLayoutRouteWithChildren
}

const AppAuthDashboardRouteChildren: AppAuthDashboardRouteChildren = {
  AppAuthDashboardLayoutRoute: AppAuthDashboardLayoutRouteWithChildren,
}

const AppAuthDashboardRouteWithChildren =
  AppAuthDashboardRoute._addFileChildren(AppAuthDashboardRouteChildren)

interface AppAuthOnboardingLayoutRouteChildren {
  AppAuthOnboardingLayoutUsernameRoute: typeof AppAuthOnboardingLayoutUsernameRoute
}

const AppAuthOnboardingLayoutRouteChildren: AppAuthOnboardingLayoutRouteChildren =
  {
    AppAuthOnboardingLayoutUsernameRoute: AppAuthOnboardingLayoutUsernameRoute,
  }

const AppAuthOnboardingLayoutRouteWithChildren =
  AppAuthOnboardingLayoutRoute._addFileChildren(
    AppAuthOnboardingLayoutRouteChildren,
  )

interface AppAuthOnboardingRouteChildren {
  AppAuthOnboardingLayoutRoute: typeof AppAuthOnboardingLayoutRouteWithChildren
}

const AppAuthOnboardingRouteChildren: AppAuthOnboardingRouteChildren = {
  AppAuthOnboardingLayoutRoute: AppAuthOnboardingLayoutRouteWithChildren,
}

const AppAuthOnboardingRouteWithChildren =
  AppAuthOnboardingRoute._addFileChildren(AppAuthOnboardingRouteChildren)

interface AppAuthRouteChildren {
  AppAuthGameRoute: typeof AppAuthGameRouteWithChildren
  AppAuthDashboardRoute: typeof AppAuthDashboardRouteWithChildren
  AppAuthOnboardingRoute: typeof AppAuthOnboardingRouteWithChildren
}

const AppAuthRouteChildren: AppAuthRouteChildren = {
  AppAuthGameRoute: AppAuthGameRouteWithChildren,
  AppAuthDashboardRoute: AppAuthDashboardRouteWithChildren,
  AppAuthOnboardingRoute: AppAuthOnboardingRouteWithChildren,
}

const AppAuthRouteWithChildren =
  AppAuthRoute._addFileChildren(AppAuthRouteChildren)

interface AppLoginLayoutRouteChildren {
  AppLoginLayoutIndexRoute: typeof AppLoginLayoutIndexRoute
}

const AppLoginLayoutRouteChildren: AppLoginLayoutRouteChildren = {
  AppLoginLayoutIndexRoute: AppLoginLayoutIndexRoute,
}

const AppLoginLayoutRouteWithChildren = AppLoginLayoutRoute._addFileChildren(
  AppLoginLayoutRouteChildren,
)

interface AppLoginRouteChildren {
  AppLoginLayoutRoute: typeof AppLoginLayoutRouteWithChildren
}

const AppLoginRouteChildren: AppLoginRouteChildren = {
  AppLoginLayoutRoute: AppLoginLayoutRouteWithChildren,
}

const AppLoginRouteWithChildren = AppLoginRoute._addFileChildren(
  AppLoginRouteChildren,
)

interface AppRouteChildren {
  AppAuthRoute: typeof AppAuthRouteWithChildren
  AppLoginRoute: typeof AppLoginRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppAuthRoute: AppAuthRouteWithChildren,
  AppLoginRoute: AppLoginRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
